---
- name: Include OS-specific variables (Debian)
  ansible.builtin.include_vars: "Debian.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat)
  ansible.builtin.include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'

- name: Include OS-specific variables (Amazon)
  ansible.builtin.include_vars: "{{ ansible_os_family }}-7.yml"
  when: ansible_distribution == 'Amazon'

- name: Setup
  ansible.builtin.include_tasks: "setup-{{ ansible_os_family }}.yml"
