---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - libaio1*
    state: present
  become: true

- name: Download Instant Client basic
  ansible.builtin.get_url:
    url: "{{ oracle_instantclient_basic_url }}"
    dest: /tmp/instantclient-basic.zip
    mode: 0655
    checksum: "{{ oracle_instantclient_basic_checksum }}"
  changed_when: false

- name: Download Instant Client SDK
  ansible.builtin.get_url:
    url: "{{ oracle_instantclient_sdk_url }}"
    dest: /tmp/instantclient-sdk.zip
    mode: 0655
    checksum: "{{ oracle_instantclient_sdk_checksum }}"
  changed_when: false

- name: Ensure Instant Client folder exists
  ansible.builtin.file:
    path: "{{ oracle_instantclient_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Extract Instant Client basic archive
  ansible.builtin.unarchive:
    src: /tmp/instantclient-basic.zip
    dest: "{{ oracle_instantclient_basepath }}"
    creates: "{{ oracle_instantclient_path }}/libclntsh.so"
    owner: root
    group: root
    remote_src: yes
  become: true

- name: Extract Instant Client SDK archive
  ansible.builtin.unarchive:
    src: /tmp/instantclient-sdk.zip
    dest: "{{ oracle_instantclient_basepath }}"
    creates: "{{ oracle_instantclient_path }}/sdk/include/oratypes.h"
    owner: root
    group: root
    remote_src: yes
  become: true

- name: Create Instant Client symlink
  ansible.builtin.file:
    src: "{{ oracle_instantclient_path }}"
    dest: "{{ oracle_instantclient_symlink }}"
    owner: root
    group: root
    state: link
  become: true

- name: Create dynamic linker configuration
  ansible.builtin.template:
    src: oracle-instantclient.conf.j2
    dest: /etc/ld.so.conf.d/oracle-instantclient.conf
    owner: root
    group: root
    mode: 'u=rw,go=r'
  become: true
  notify: Execute ldconfig

- name: Remove Instant Client archives
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/instantclient-basic.zip
    - /tmp/instantclient-sdk.zip
  changed_when: false
